version: "2"
services:
  postgres:
    image: postgres:14
    container_name: my_postgres
    expose:
      - 5436
    volumes:
      - data:/var/lib/postgresql/data
      - ${VOLUME_PATH}/backup:/backup
    environment:
      - POSTGRES_DB=acme-store
      - POSTGRES_PASSWORD=password
    restart: unless-stopped

  backup:
    build: .
    image: ghcr.io/mentos1386/postgres-cron-backup
    depends_on:
      - postgres
    volumes:
      - ./backup:/backup
    environment:
      - POSTGRES_HOST=my_postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=password
      - MAX_BACKUPS=1
      - INIT_BACKUP=1
      - CRON_TIME=0 0 * * *
    restart: unless-stopped

  restore:
    build: .
    image: ghcr.io/mentos1386/postgres-cron-backup
    command: "/restore.sh /backup/latest.acme-store.sql.gz"
    depends_on:
      - postgres
    volumes:
      - ./backup:/backup
    environment:
      - POSTGRES_HOST=my_postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=password
      - POSTGRES_DATABASE=acme-store
  
volumes: 
  data:
